<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190613193735 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE account_category');
        $this->addSql('DROP TABLE account_source');
        $this->addSql('DROP TABLE account_status');
        $this->addSql('DROP TABLE account_type');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE address_country');
        $this->addSql('DROP TABLE address_state');
        $this->addSql('DROP TABLE affix');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE applicationtype');
        $this->addSql('DROP TABLE breed');
        $this->addSql('DROP TABLE club');
        $this->addSql('DROP TABLE clubhasbreed');
        $this->addSql('DROP TABLE clubhasdisciplines');
        $this->addSql('DROP TABLE clubtype');
        $this->addSql('DROP TABLE discipline');
        $this->addSql('DROP TABLE dog');
        $this->addSql('DROP TABLE dogbreeder');
        $this->addSql('DROP TABLE dogowner');
        $this->addSql('DROP TABLE entity_class');
        $this->addSql('DROP TABLE judgeinfo');
        $this->addSql('DROP TABLE litter');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE log_type');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE notification');
        $this->addSql('ALTER TABLE contact CHANGE manager manager INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE account (id INT AUTO_INCREMENT NOT NULL, account_category_id INT DEFAULT NULL, account_source_id INT DEFAULT NULL, account_status_id INT DEFAULT NULL, account_type_id INT DEFAULT NULL, address_billing_id INT DEFAULT NULL, address_shipping_id INT DEFAULT NULL, company_id INT DEFAULT NULL, user_assigned_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, account_number VARCHAR(25) DEFAULT NULL COLLATE utf8mb4_unicode_ci, blocked TINYINT(1) DEFAULT \'0\', contact_number VARCHAR(25) DEFAULT NULL COLLATE utf8mb4_unicode_ci, fax_number VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, purchase_order TINYINT(1) DEFAULT \'0\', vat_number VARCHAR(25) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_7D3656A4484BD390 (user_assigned_id), INDEX IDX_7D3656A4F987D8A8 (user_created_id), INDEX IDX_7D3656A4B746C43A (account_source_id), INDEX IDX_7D3656A4C6798DB (account_type_id), INDEX IDX_7D3656A45F48D033 (address_shipping_id), INDEX IDX_7D3656A4979B1AD6 (company_id), INDEX IDX_7D3656A448F4B750 (entity_class_id), INDEX IDX_7D3656A4316B011F (user_updated_id), INDEX IDX_7D3656A4C30161E1 (account_category_id), INDEX IDX_7D3656A4498DD8E6 (account_status_id), INDEX IDX_7D3656A4439FD419 (address_billing_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE account_category (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, url_name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, icon VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_order INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_7E82FB77F987D8A8 (user_created_id), INDEX IDX_7E82FB77316B011F (user_updated_id), INDEX IDX_7E82FB7748F4B750 (entity_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE account_source (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, url_name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, icon VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_order INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_78BEB100F987D8A8 (user_created_id), INDEX IDX_78BEB10048F4B750 (entity_class_id), INDEX IDX_78BEB100316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE account_status (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, url_name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, icon VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_order INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_5C34AB6FF987D8A8 (user_created_id), INDEX IDX_5C34AB6F48F4B750 (entity_class_id), INDEX IDX_5C34AB6F316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE account_type (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, url_name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, icon VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_order INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_4DD083F987D8A8 (user_created_id), INDEX IDX_4DD08348F4B750 (entity_class_id), INDEX IDX_4DD083316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE address (id INT AUTO_INCREMENT NOT NULL, state_id INT DEFAULT NULL, country_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, address_line_1 VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, address_line_2 VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, postal_code VARCHAR(25) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_D4E6F81F92F3E70 (country_id), INDEX IDX_D4E6F81F987D8A8 (user_created_id), INDEX IDX_D4E6F815D83CC1 (state_id), INDEX IDX_D4E6F8148F4B750 (entity_class_id), INDEX IDX_D4E6F81316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE address_country (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, country_code VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_8963EFEF987D8A8 (user_created_id), INDEX IDX_8963EFE48F4B750 (entity_class_id), INDEX IDX_8963EFE316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE address_state (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_9436A5DB48F4B750 (entity_class_id), INDEX IDX_9436A5DB316B011F (user_updated_id), INDEX IDX_9436A5DBF987D8A8 (user_created_id), INDEX IDX_9436A5DBF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE affix (id INT AUTO_INCREMENT NOT NULL, user_affix_owner_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, affix_renewal_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_1B47B04948F4B750 (entity_class_id), INDEX IDX_1B47B049316B011F (user_updated_id), INDEX IDX_1B47B049BA67594C (user_affix_owner_id), INDEX IDX_1B47B049F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application (id INT AUTO_INCREMENT NOT NULL, user_application_member_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, application_renewal_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_22C7521648F4B750 (entity_class_id), INDEX IDX_22C75216316B011F (user_updated_id), INDEX IDX_22C752163192E481 (user_application_member_id), INDEX IDX_22C75216F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE applicationtype (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, fee NUMERIC(10, 0) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_677D0AE7F987D8A8 (user_created_id), INDEX IDX_677D0AE748F4B750 (entity_class_id), INDEX IDX_677D0AE7316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE breed (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_396EA74BF987D8A8 (user_created_id), INDEX IDX_396EA74B48F4B750 (entity_class_id), INDEX IDX_396EA74B316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE club (id INT AUTO_INCREMENT NOT NULL, user_club_owner_id INT DEFAULT NULL, user_club_chairman_id INT DEFAULT NULL, user_club_secretary_id INT DEFAULT NULL, user_clib_teasurer_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_18DC974C6EEC2E19 (user_club_chairman_id), INDEX IDX_18DC974C658B3464 (user_clib_teasurer_id), INDEX IDX_18DC974CF987D8A8 (user_created_id), INDEX IDX_18DC974C93096600 (user_club_owner_id), INDEX IDX_18DC974C200D2E69 (user_club_secretary_id), INDEX IDX_18DC974C48F4B750 (entity_class_id), INDEX IDX_18DC974C316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE clubhasbreed (id INT AUTO_INCREMENT NOT NULL, clubhasbreed_club_id INT DEFAULT NULL, clubhasbreed_breed_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_A150F15E8ABF2C59 (clubhasbreed_breed_id), INDEX IDX_A150F15EF987D8A8 (user_created_id), INDEX IDX_A150F15E316B011F (user_updated_id), INDEX IDX_A150F15E6880E584 (clubhasbreed_club_id), INDEX IDX_A150F15E48F4B750 (entity_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE clubhasdisciplines (id INT AUTO_INCREMENT NOT NULL, clubhasdisciplines_club_id INT DEFAULT NULL, clubhasdisciplines_breed_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_2C3D1C969C5F259 (clubhasdisciplines_breed_id), INDEX IDX_2C3D1C96F987D8A8 (user_created_id), INDEX IDX_2C3D1C96316B011F (user_updated_id), INDEX IDX_2C3D1C96C1DB2293 (clubhasdisciplines_club_id), INDEX IDX_2C3D1C9648F4B750 (entity_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE clubtype (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_3B93A3A2F987D8A8 (user_created_id), INDEX IDX_3B93A3A248F4B750 (entity_class_id), INDEX IDX_3B93A3A2316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE discipline (id INT AUTO_INCREMENT NOT NULL, user_discipline_owner_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_3AE3EDEF48F4B750 (entity_class_id), INDEX IDX_3AE3EDEF316B011F (user_updated_id), INDEX IDX_3AE3EDEF3648DB34 (user_discipline_owner_id), INDEX IDX_3AE3EDEFF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE dog (id INT AUTO_INCREMENT NOT NULL, dog_affix_id INT DEFAULT NULL, dog_breed_id INT DEFAULT NULL, dog_litter_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, dogship_renewal_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, dog_owner_id INT DEFAULT NULL, INDEX IDX_B9617F9D5E8BA58A (dog_litter_id), INDEX IDX_B9617F9DF987D8A8 (user_created_id), INDEX IDX_B9617F9D845ED698 (dog_affix_id), INDEX IDX_B9617F9D48F4B750 (entity_class_id), INDEX IDX_B9617F9D316B011F (user_updated_id), INDEX IDX_B9617F9D1663DCD8 (dog_owner_id), INDEX IDX_B9617F9DC0EB1E2E (dog_breed_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE dogbreeder (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, user_dogbreeder_id INT DEFAULT NULL, INDEX IDX_C24F3E348F4B750 (entity_class_id), INDEX IDX_C24F3E3316B011F (user_updated_id), INDEX IDX_C24F3E3F987D8A8 (user_created_id), INDEX IDX_C24F3E3DCDA181F (user_dogbreeder_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE dogowner (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, dogownership_transfer_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, user_dogowner_id INT DEFAULT NULL, INDEX IDX_68792EF548F4B750 (entity_class_id), INDEX IDX_68792EF5316B011F (user_updated_id), INDEX IDX_68792EF5216190C3 (user_dogowner_id), INDEX IDX_68792EF5F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE entity_class (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, bundle VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_page_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_content_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_array_page_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_array_content_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_form_page_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_form_content_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_form_array_page_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_form_array_content_title VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, url_name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, icon VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, entity_order INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_41BF2C66F987D8A8 (user_created_id), INDEX IDX_41BF2C66316B011F (user_updated_id), INDEX IDX_41BF2C6648F4B750 (entity_class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE judgeinfo (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_3820EC9FF987D8A8 (user_created_id), INDEX IDX_3820EC9F48F4B750 (entity_class_id), INDEX IDX_3820EC9F316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE litter (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_4C5E063DF987D8A8 (user_created_id), INDEX IDX_4C5E063D48F4B750 (entity_class_id), INDEX IDX_4C5E063D316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, log_type_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, url VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, client_ip VARCHAR(15) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_8F3F68C548F4B750 (entity_class_id), INDEX IDX_8F3F68C5316B011F (user_updated_id), INDEX IDX_8F3F68C5FD81B404 (log_type_id), INDEX IDX_8F3F68C5F987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE log_type (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_9DB0B95CF987D8A8 (user_created_id), INDEX IDX_9DB0B95C48F4B750 (entity_class_id), INDEX IDX_9DB0B95C316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE member (id INT AUTO_INCREMENT NOT NULL, user_member_id INT DEFAULT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, membership_renewal_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_7748FF4E48F4B750 (entity_class_id), INDEX IDX_7748FF4E316B011F (user_updated_id), INDEX IDX_7748FF4E75775E1A (user_member_id), INDEX IDX_7748FF4EF987D8A8 (user_created_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, entity_class_id INT DEFAULT NULL, user_created_id INT DEFAULT NULL, user_updated_id INT DEFAULT NULL, notification_type VARCHAR(25) NOT NULL COLLATE utf8mb4_unicode_ci, sender_address VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, recipient_address VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, subject VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, content LONGTEXT NOT NULL COLLATE utf8mb4_unicode_ci, recipient_number VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, schedule_date DATE DEFAULT NULL, date_sent DATETIME DEFAULT NULL, sent_status VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8mb4_unicode_ci, description VARCHAR(2550) DEFAULT NULL COLLATE utf8mb4_unicode_ci, locked TINYINT(1) DEFAULT \'0\', date_created_id DATETIME NOT NULL, date_updated_id DATETIME DEFAULT NULL, INDEX IDX_BF5476CAF987D8A8 (user_created_id), INDEX IDX_BF5476CA48F4B750 (entity_class_id), INDEX IDX_BF5476CA316B011F (user_updated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE post');
        $this->addSql('ALTER TABLE contact CHANGE manager manager VARCHAR(225) DEFAULT NULL COLLATE utf8mb4_unicode_ci');
    }
}
